function linear_plotter(plotname,xdata,ydata,group,xtitle,ytitle,title,ylim,ytick,leg_pos)

g = gramm('x',xdata,'y',ydata,'color',group,'linestyle',group);
g.set_title(title);
g.set_names('x',xtitle,'y',ytitle,'color','','linestyle','');

g.geom_line();
%g.geom_point();

%g.set_color_options('map',[189/255,189/255,189/255]);
g.set_text_options( ...
    'font','Helvetica',...
    'interpreter','tex',...
    'base_size',18,...
    'label_scaling',1,...
    'legend_scaling',1,...
    'legend_title_scaling',1,...
    'facet_scaling',1,...
    'title_scaling',1,... 
    'big_title_scaling',1);

g.set_layout_options( ...
    'legend_position',leg_pos);

g.set_color_options('legend','merge')

g.axe_property( ...
    'YLim',ylim,...
    'YTick',ytick,...
    'YMinorTick','on',...
    'XLim',[25 90],...
    'XTick',30:10:90,...
    'XMinorTick','on');


figure('Position',[100 100 650 450]);
g.draw();

g.export(...
    'file_name',plotname,...
    'file_type','png');

close all

end